app/users/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed
from wtforms import (StringField, SubmitField, HiddenField, PasswordField, BooleanField,
                     FileField, DateTimeField, SelectField)
from wtforms.ext.sqlalchemy.fields import QuerySelectMultipleField, QuerySelectField
from wtforms.validators import DataRequired, Email, Length, EqualTo, Optional
from .validators import UniqueUsername, UniqueEmail
from ..auth.models import Role
from flask_babel import lazy_gettext as _l


class ProfileForm(FlaskForm):
    id = HiddenField(label='ID')
    fullname = StringField(label=_l('Full name'), validators=[DataRequired()])
    username = StringField(label=_l('Username'), validators=[DataRequired(), UniqueUsername()])
    email = StringField(label=_l('Email'), validators=[DataRequired(), Email(), UniqueEmail()])
    password = PasswordField(label=_l('Password'), validators=[Optional(), Length(min=8)])
    confirm_password = PasswordField(label=_l('Confirm Password'), validators=[EqualTo('password')])
    status = BooleanField(label=_l('Status'))
    image = FileField(label=_l('Image'), validators=[FileAllowed(['jpg', 'jpeg', 'png'], 'jpg or png')])
    roles = QuerySelectMultipleField(_l('Roles'))
    createdat = DateTimeField('createdat')
    delete = BooleanField(label=_l('Delete'))
    submit = SubmitField(_l('Update'))

    def __init__(self, *args, **kwargs):
        super().__init__(**kwargs)
        self.roles.query = Role.query.all()


class AddUserForm(ProfileForm):
    password = PasswordField(label=_l('Password'), validators=[Length(min=8)])
    submit = SubmitField(_l('Save'))


class SearchUserForm(FlaskForm):
    fullname = StringField(label=_l('Full name'))
    email = StringField(label=_l('Email'))
    role = QuerySelectField(label=_l('Role'), allow_blank=True, blank_text='')
    status = SelectField(label=_l('Status'), choices=[('', ''), (1, 'Active'), (0, 'Inactive')])

    def __init__(self, *args, **kwargs):
        super().__init__(**kwargs)
        self.role.query = Role.query.all()

app/users/__init__.py
from flask import Blueprint

bp = Blueprint('users', __name__)

from . import routes, forms

app/users/routes.py
from flask import render_template, url_for, flash, redirect, request, current_app
from . import bp
from flask_login import login_required
from ..auth.decorators import role_required
from ..auth.models import User, Role
from .forms import ProfileForm, AddUserForm, SearchUserForm
from flask_babel import _
import os
import uuid
import re


@bp.route('/users')
@login_required
@role_required('Administrator')
def list():
    # define search form and populate previous search criteria
    form = SearchUserForm(data=request.args.items())
    # because 'role' QuerySelectField has been populated with objects of type <Role>
    # it won't be selected just with the id from query string (previous search criteria)
    # We get object Role from id
    if request.args.get('role'):
        role = Role.query.get(request.args.get('role'))
        form.role.data = role

    # parse filters and select User records
    query_user = User.query
    if request.args:
        for parameter in request.args.items():
            if parameter[0] == 'email' and parameter[1]:
                query_user = query_user.filter(User.email.like('%' + parameter[1] + '%'))
            elif parameter[0] == 'fullname' and parameter[1]:
                query_user = query_user.filter(User.fullname.like('%' + parameter[1] + '%'))
            elif parameter[0] == 'role' and parameter[1] != '__None':
                query_user = query_user.join('roles').filter(Role.id == parameter[1])
            elif parameter[0] == 'status' and parameter[1] != '':
                query_user = query_user.filter(User.status == parameter[1])
    page = request.args.get('page', 1, type=int)
    users = query_user.order_by(User.id).paginate(page, 10, False)

    # pass search filter in pagination
    query_string = re.sub('page=\d*&*', '', request.query_string.decode('utf-8'))
    return render_template('users/list.html', users=users, query_string=query_string, form=form)


@bp.route('/user/<int:id>', methods=['GET', 'POST'])
@login_required
@role_required('Administrator')
def update(id):
    user = User.query.get(id)  # type: User
    form = ProfileForm(obj=user)

    if form.validate_on_submit():
        user.fullname = form.fullname.data
        user.username = form.username.data
        if form.password.data:
            user.set_password(form.password.data)
        user.email = form.email.data
        user.status = form.status.data
        user.roles = form.roles.data
        if form.delete.data:
            delete_image(user.image)
            user.image = None
        if form.image.data:
            delete_image(user.image)
            user.image = upload_image(form.image.data)
        user.save()
        flash(_('User saved successfully.'), category='success')
        return redirect(url_for('users.list'))
    return render_template('users/update.html', form=form)


@bp.route('/user/add', methods=['GET', 'POST'])
@login_required
@role_required('Administrator')
def add():
    form = AddUserForm()
    if form.validate_on_submit():
        user = User()
        user.fullname = form.fullname.data
        user.username = form.username.data
        user.set_password(form.password.data)
        user.email = form.email.data
        user.status = form.status.data
        user.roles = form.roles.data
        user.image = upload_image(form.image.data)
        user.save()
        flash(_('User saved successfully.'), category='success')
        return redirect(url_for('users.list'))

    return render_template('users/add.html', form=form)


def upload_image(imagedata):
    if imagedata:
        extension = os.path.splitext(imagedata.filename)[1]
        unique_filename = uuid.uuid4().hex + extension
        imagedata.save(os.path.join(current_app.config['UPLOAD_FOLDER'], unique_filename))
        return unique_filename
    return None


def delete_image(image):
    if image and os.path.exists(os.path.join(current_app.config['UPLOAD_FOLDER'], image)):
        os.remove(os.path.join(current_app.config['UPLOAD_FOLDER'], image))
        return True
    return False

app/templates/users/add.html
{% extends 'layout/layout.html' %}
{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{{ url_for('users.list') }}">Users</a></li>
    <li class="breadcrumb-item active">{{ _('Add user') }}</li>
{% endblock %}
{% block content %}
    <div class="card mt-3">
        <div class="card-header"><h3>{{ _('Create a new user') }}</h3></div>
        <div class="card-body">
            <form method="post" action="" enctype="multipart/form-data" novalidate>
                <div class="form-group">
                    {{ form.hidden_tag() }}
                </div>
                <div class="form-group">
                    {{ form.fullname.label }}
                    {{ form.fullname(class='form-control') }}
                    {% for error in form.fullname.errors %}
                        <small class="form-text text-danger">{{ error }}</small>
                    {% endfor %}
                </div>
                <div class="form-group">
                    {{ form.email.label }}
                    {{ form.email(class='form-control') }}
                    <ul>
                    {% for error in form.email.errors %}
                        <li><small class="form-text text-danger">{{ error }}</small></li>
                    {% endfor %}
                    </ul>
                </div>
                <div class="form-group">
                    {{ form.username.label }}
                    {{ form.username(class='form-control') }}
                    <ul>
                    {% for error in form.username.errors %}
                        <li><small class="form-text text-danger">{{ error }}</small></li>
                    {% endfor %}
                    </ul>
                </div>
                <div class="form-group">
                    {{ form.password.label }}
                    {{ form.password(class='form-control', placeholder=_('type at least 8 characters')) }}
                    <ul>
                    {% for error in form.password.errors %}
                        <li><small class="form-text text-danger">{{ error }}</small></li>
                    {% endfor %}
                    </ul>
                </div>
                <div class="form-group">
                    {{ form.confirm_password.label }}
                    {{ form.confirm_password(class='form-control', placeholder=_('type at least 8 characters')) }}
                    <ul>
                    {% for error in form.confirm_password.errors %}
                        <li><small class="form-text text-danger">{{ error }}</small></li>
                    {% endfor %}
                    </ul>
                </div>
                <div class="form-group">
                    {{ form.roles.label }}
                    {{ form.roles(class='form-control') }}
                </div>
                <div class="form-group">
                    {{ form.status.label }}
                    <div>{{ form.status }}</div>
                </div>
                <div class="form-group">
                    {{ form.image.label }}
                    {{ form.image(class='form-control', style='height: auto;') }}
                    {% for error in form.image.errors %}
                        <small class="form-text text-danger">{{ error }}</small>
                    {% endfor %}
                </div>
                <div>
                    <button type="button" class="btn btn-primary float-right ml-1" id="btn-cancel">{{ _('Cancel') }}</button>
                    {{ form.submit(class='btn btn-success float-right') }}
                </div>

            </form>
        </div>
    </div>
{% endblock %}

{% block inlinejs %}
<script>
    $(document).ready(function () {
        $("#roles").select2();
        $("#status").bootstrapSwitch();
        $("#btn-cancel").on("click", function () {
            window.location.assign("{{ url_for('users.list') }}");
        });
    });
</script>
{% endblock %}

app/templates/users/list.html
{% extends 'layout/layout.html' %}
{% from 'macro/pagination.html' import render_pagination %}
{% block breadcrumb %}
    <li class="breadcrumb-item active">{{ _('Users') }}</li>
{% endblock %}
{% block content %}
    <div style="margin-bottom: 10px;">
        <a href="#search-filters" class="btn btn-secondary float-right ml-1" data-toggle="collapse" role="button" >
                {{ _('Filters') }}
        </a>
        <div class="clearfix"></div>
        <div class="collapse" id="search-filters">
            <form method="get">
                <div class="form-group">
                    {{ form.fullname.label }}
                    {{ form.fullname(class='form-control') }}
                </div>
                <div class="form-group">
                    {{ form.email.label }}
                    {{ form.email(class='form-control') }}
                </div>
                <div class="form-group">
                    {{ form.role.label }}
                    {{ form.role(class='form-control') }}
                </div>
                <div class="form-group">
                    {{ form.status.label }}
                    {{ form.status(class='form-control') }}
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-success float-right ml-1">{{ _('Search') }}</button>
                    <a href="{{ url_for('users.list') }}" class="btn btn-light float-right ml-1">{{ _('Reset') }}</a>
                    <div class="clearfix"></div>
                </div>
            </form>
        </div>
    </div>
    <div class="card">
        <div class="card-header">
            <h3>{{ _('List of users') }}</h3>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table">
                    <thead class="thead-ssecondary">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">{{ _('Full name') }}</th>
                        <th scope="col">{{ _('Username') }}</th>
                        <th scope="col">{{ _('Email') }}</th>
                        <th scope="col" class="text-center">{{ _('Status') }}</th>
                        <th scope="col" class="text-center">{{ _('Edit') }}</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for user in users.items %}
                        <tr>
                            <th scope="row"><a href="{{ url_for('users.update', id=user.id) }}">{{ user.id }}</a></th>
                            <td>{{ user.fullname }}</td>
                            <td>{{ user.username }}</td>
                            <td>{{ user.email }}</td>
                            <td class="text-center">
                                {% if user.status %}
                                    <i class="fa fa-check text-success" title="Active">&nbsp;</i>
                                {% else %}
                                    <i class="fa fa-ban text-danger" title="Inactive"></i>
                                {% endif %}
                            </td>
                            <td class="text-center">
                                <a href="{{ url_for('users.update', id=user.id) }}" class="btn btn-info" title="{{ _('Edit user') }}">
                                    <i class="fa fa-edit"></i></a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                    <tfoot>
                        <tr>
                            <td colspan="5">
                                {{ render_pagination(users, 'users.list', query_string) }}
                            </td>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

{% block inlinejs %}
    <script>
        $(document).ready(function () {
            {% with messages = get_flashed_messages() %}
            {% for message in messages %}
            PNotify.success({
                title: 'Saving user',
                text: '{{ message }}',
                styling: 'material',
            });
            {% endfor %}
            {% endwith %}

            $("#role, #status").select2({
                width: '100%'
            });
        });
    </script>
{% endblock %}

app/templates/users/update.html
{% extends 'layout/layout.html' %}
{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{{ url_for('users.list') }}">Users</a></li>
    <li class="breadcrumb-item active">{{ _('Update user') }}</li>
{% endblock %}
{% block content %}
    <div class="card mt-3 clearfix">
        <div class="card-header">
            <h3 class="float-left">{{ _('Update user with') }} {{ form.id.label }}: #{{ form.id.data }}</h3>
            <span class="float-right"><strong>{{ _('Created') }}:</strong>
                {{ form.createdat.data | localdatetime }}
            </span>
        </div>
        <div class="card-body">
            <form method="post" action="" enctype="multipart/form-data" novalidate>
                <div class="form-group">
                    {{ form.hidden_tag() }}
                </div>
                <div class="form-group">
                    {{ form.fullname.label }}
                    {{ form.fullname(class='form-control') }}
                    {% for error in form.fullname.errors %}
                        <small class="form-text text-danger">{{ error }}</small>
                    {% endfor %}
                </div>
                <div class="form-group">
                    {{ form.email.label }}
                    {{ form.email(class='form-control') }}
                    <ul>
                    {% for error in form.email.errors %}
                        <li><small class="form-text text-danger">{{ error }}</small></li>
                    {% endfor %}
                    </ul>
                </div>
                <div class="form-group">
                    {{ form.username.label }}
                    {{ form.username(class='form-control') }}
                    <ul>
                    {% for error in form.username.errors %}
                        <li><small class="form-text text-danger">{{ error }}</small></li>
                    {% endfor %}
                    </ul>
                </div>
                <div class="form-group">
                    {{ form.password.label }}
                    {{ form.password(class='form-control', placeholder=_('type at least 8 characters')) }}
                    <ul>
                    {% for error in form.password.errors %}
                        <li><small class="form-text text-danger">{{ error }}</small></li>
                    {% endfor %}
                    </ul>
                </div>
                <div class="form-group">
                    {{ form.confirm_password.label }}
                    {{ form.confirm_password(class='form-control', placeholder=_('type at least 8 characters')) }}
                    <ul>
                    {% for error in form.confirm_password.errors %}
                        <li><small class="form-text text-danger">{{ error }}</small></li>
                    {% endfor %}
                    </ul>
                </div>
                <div class="form-group">
                    {{ form.roles.label }}
                    {{ form.roles(class='form-control') }}
                </div>
                <div class="form-group">
                    {{ form.status.label }}
                    <div>{{ form.status }}</div>
                </div>
                {% if form.image.data is not none %}
                    <div class="form-group">
                        <label>{{ _('Existing image') }}</label>&nbsp;&nbsp;&nbsp;
                        <div class="form-control">
                            <span class="fa fa-image" aria-hidden="true" data-image-url="{{ form.image.data }}"></span>
                            &nbsp;&nbsp;&nbsp;
                            {{ form.delete }}&nbsp;{{ form.delete.label }}
                        </div>
                    </div>
                {% endif %}
                <div class="form-group">
                    {{ form.image.label }}
                    {{ form.image(class='form-control', style='height: auto;') }}
                    {% for error in form.image.errors %}
                        <small class="form-text text-danger">{{ error }}</small>
                    {% endfor %}
                </div>
                <div>
                    <button type="button" class="btn btn-primary float-right ml-1" id="btn-cancel">{{ _('Cancel') }}</button>
                    {{ form.submit(class='btn btn-success float-right') }}
                </div>
            </form>
        </div>
    </div>
{% endblock %}

{% block inlinejs %}
<script>
    $(document).ready(function () {
        $("#roles").select2();
        $("#status").bootstrapSwitch();
        $("#btn-cancel").on("click", function () {
            window.location.assign("{{ request.referrer }}");
        });

       $(".fa-image").popover({
                'container': 'body',
                'title': 'Photo',
                'html': true,
                'trigger': 'hover',
                'content': function() {
                        return '<img src="{{ url_for('static', filename='images/users/' ~ form.image.data) }}' + '" style="width:200px;" alt="user image">'
                    }
            });

    });
</script>
{% endblock %}