app/articles/models.py
from .. import db
from datetime import datetime


class Article(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(128), nullable=False)
    slug = db.Column(db.String(256))
    body = db.Column(db.Text)
    image = db.Column(db.String(256))
    status = db.Column(db.Boolean)
    createdat = db.Column(db.DateTime, default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id', ondelete='CASCADE'))

    def save(self):
        db.session.add(self)
        db.session.commit()

    def delete(self):
        db.session.delete(self)
        db.session.commit()

    def __repr__(self):
        return '<Article: {}, {}>'.format(self.id, self.title)

app/main/models.py
from .. import db


class Config(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    entity = db.Column(db.String(128), unique=True)
    value = db.Column(db.String(256))

    def __init(self, entity, value = ''):
        self.entity = entity
        self.value = value

    def save(self):
        db.session.add(self)
        db.session.commit()

    def __repr__(self):
        return '<Config: {}, {}>'.format(self.entity, self.value)

app/articles/forms.py
from flask_wtf import FlaskForm
from wtforms import (
    StringField, SubmitField, BooleanField, FileField, TextAreaField, HiddenField, DateTimeField, SelectField
)
from wtforms.ext.sqlalchemy.fields import QuerySelectField
from wtforms.validators import Length
from flask_wtf.file import FileAllowed
from flask_babel import lazy_gettext as _l
from ..auth.models import User


class AddForm(FlaskForm):
    title = StringField(label=_l('Title'), validators=[Length(min=4, max=128)])
    slug = StringField(label=_l('Slug'), validators=[Length(min=3, max=256)])
    body = TextAreaField(label=_l('Body'))
    status = BooleanField(label=_l('Status'))
    image = FileField(label=_l('Image'), validators=[FileAllowed(['jpg', 'jpeg', 'png'], 'jpg or png')])
    submit = SubmitField(label=_l('Submit'))


class UpdateForm(AddForm):
    id = HiddenField(label='id')
    createdat = DateTimeField(label=_l('Created at'))
    del_image = BooleanField(label=_l('Delete'))


class SearchForm(FlaskForm):
    title = StringField(label='Title', validators=[Length(min=4, max=128)])
    author = QuerySelectField(label=_l('Author'), allow_blank=True, blank_text='')
    status = SelectField(label=_l('Status'), choices=[('', ''),(1, 'Active'),(0, 'Inactive')])

    def __init__(self, *args, **kwargs):
        super().__init__(**kwargs)
        self.author.query = User.query.all()

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import BooleanField, SubmitField
from flask_babel import lazy_gettext as _l


class SettingsForm(FlaskForm):
    offline = BooleanField(label=_l('Offline'))
    registration = BooleanField(label=_l('Registration'))
    submit = SubmitField(label=_l('Save'))

app/articles/__init__.py
from flask import Blueprint

bp = Blueprint('articles', __name__)

from . import models, forms, routes

app/articles/routes.py
from .models import Article
from .forms import AddForm, UpdateForm, SearchForm
from flask_login import current_user, login_required
from ..auth.decorators import role_required
from . import bp
from flask import render_template, request, flash, redirect, url_for, abort, current_app
from flask_babel import _
import os, uuid, re
from ..auth.models import User


@bp.route('/articles')
@login_required
@role_required('Administrator', 'Editor', 'User')
def list_view():
    # define search form and populate previous search criteria
    form = SearchForm(data=request.args.items())
    # because 'author' QuerySelectField has been populated with objects of type <User>
    # it won't be selected just with the id from query string (previous search criteria)
    # We get object User from id
    if request.args.get('author'):
        author = User.query.get(request.args.get('author'))
        form.author.data = author

    query_article = Article.query
    if request.args:
        for parameter in request.args.items():
            if parameter[0] == 'title' and parameter[1]:
                query_article = query_article.filter(Article.title.like('%' + parameter[1] + '%'))
            elif parameter[0] == 'author' and parameter[1] != '__None':
                query_article = query_article.join('author').filter(User.id == parameter[1])
            elif parameter[0] == 'status' and parameter[1] != '':
                query_article = query_article.filter(Article.status == parameter[1])
    page = request.args.get('page', 1, type=int)
    if current_user.has_role('Administrator') or current_user.has_role('Editor'):
        articles = query_article.order_by(Article.createdat).paginate(page, 10, False)
    else:
        articles = query_article.filter_by(user_id=current_user.id).paginate(page, 10, False)
    # pass search filter in pagination
    query_string = re.sub('page=\d*&*', '', request.query_string.decode('utf-8'))
    return render_template('articles/list.html', articles=articles, form=form, query_string=query_string)


@bp.route('/article/add', methods=['GET', 'POST'])
@login_required
@role_required('Administrator', 'Editor', 'User')
def add():
    form = AddForm()
    if form.validate_on_submit():
        article = Article()
        article.title = form.title.data
        article.slug = form.slug.data
        article.body = form.body.data
        article.status = form.status.data
        article.user_id = current_user.id
        article.image = upload_image(form.image.data)
        article.save()
        flash(_('Article saved successfully.'), category='success')
        return redirect(url_for('articles.list_view'))
    return render_template('articles/add.html', form=form)


@bp.route('/article/<int:id>', methods=['GET', 'POST'])
@login_required
@role_required('Administrator', 'Editor', 'User')
def update(id):
    article = Article.query.get(id)
    form = UpdateForm(obj=article)
    if not (current_user.has_role('Administrator') or current_user.has_role(
            'Editor')) and current_user.id != article.user_id:
        abort(403)
    if form.validate_on_submit():
        article.title = form.title.data
        article.slug = form.slug.data
        article.body = form.body.data
        article.status = form.status.data
        if form.del_image.data:
            delete_image(article.image)
            article.image = None
        if form.image.data:
            delete_image(article.image)
            article.image = upload_image(form.image.data)
        article.save()
        flash(_('Article saved successfully.'), category='success')
        return redirect(url_for('articles.list_view'))
    return render_template('articles/update.html', form=form)


def upload_image(imagedata):
    if imagedata:
        extension = os.path.splitext(imagedata.filename)[1]
        unique_filename = uuid.uuid4().hex + extension
        imagedata.save(os.path.join(current_app.config['ARTICLES_UPLOAD_FOLDER'], unique_filename))
        return unique_filename
    return None


@bp.route('/article/<int:article_id>/delete', methods=['POST'])
@login_required
@role_required('Administrator', 'Editor', 'User')
def delete(article_id):
    article = Article.query.get_or_404(article_id)
    if not (current_user.has_role('Administrator') or current_user.has_role(
            'Editor')) and current_user.id != article.createdby:
        abort(403)
    article.delete()
    delete_image(article.image)
    return redirect(url_for('articles.list_view'))


def delete_image(image):
    if image and os.path.exists(os.path.join(current_app.config['ARTICLES_UPLOAD_FOLDER'], image)):
        os.remove(os.path.join(current_app.config['ARTICLES_UPLOAD_FOLDER'], image))
        return True
    return False

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from . import routes, models, forms

app/main/routes.py
from flask import render_template, request, abort, flash, send_from_directory, current_app
from flask_login import login_required
from sqlalchemy import func
from ..articles.models import Article
from ..auth.models import User
from ..auth.decorators import role_required
from ..main import bp
from .forms import SettingsForm
from .models import Config
import sys, platform, os
from distutils import util


@bp.route('/')
def index():
    articles = Article.query.filter_by(status=1).order_by(Article.createdat.desc()).all()
    return render_template('main/index.html', articles=articles)


@bp.route('/view/<int:article_id>')
def view_article(article_id):
    article = Article.query.get_or_404(article_id)
    if article.status:
        return render_template('main/article_view.html', article=article)
    abort(404)


@bp.route('/blank')
def blank():
    return render_template('main/blank.html')


@bp.route('/dashboard')
@login_required
def dashboard():
    # MySQL query
    # records = User.query.with_entities(func.date(User.created), func.count())\
    #     .group_by(func.date(User.created))\
    #     .all()

    list_articles_per_user = Article.query.join(User).with_entities(User.username, func.count()) \
        .group_by(Article.user_id) \
        .all()
    # convert [(u'dvossos', 7), (u'user1', 1), (u'user3', 2), (u'user4', 1), (u'editor1', 1)]
    # to [(u'dvossos', u'user1', u'user3', u'user4', u'editor1'), (7, 1, 2, 1, 1)]
    articles_per_user = list(zip(*list_articles_per_user))

    articles_records = Article.query.with_entities(Article.createdat, func.count()) \
        .group_by(func.date(Article.createdat)) \
        .all()
    articles = []
    articles_dates = []
    for record in articles_records:
        articles.append(record[1])
        articles_dates.append(record[0].strftime('%d/%m/%Y'))
    inactive_articles = Article.query.filter(Article.status == False).all()
    data = {
        'users_count': User.query.count(),
        'articles_count': Article.query.count(),
        'articles': articles,
        'articles_dates': articles_dates,
        'articles_per_user': articles_per_user,
        'inactive_articles': inactive_articles,
    }
    return render_template('main/dashboard.html', data=data)


@bp.route('/search', methods=['POST'])
def search_list():
    articles = Article.query\
        .filter(Article.body.like('%' + request.form['search'] + '%'))\
        .filter(Article.status == 1)\
        .all()
    return render_template('main/search_list.html', articles=articles)


@bp.route('/sysinfo', methods=['GET'])
@login_required
@role_required('Administrator')
def sysinfo():
    data = {'python_version': sys.version, 'platform_version': platform.version()}
    return render_template('main/sysinfo.html', data=data)


@bp.route('/settings', methods=['GET', 'POST'])
@login_required
@role_required('Administrator')
def settings():
    offline = Config.query.filter(Config.entity == 'offline').first()
    if offline is None:
        offline = Config(entity='offline', value='False')
    registration = Config.query.filter(Config.entity == 'registration').first()
    if registration is None:
        registration = Config(entity='registration', value='False')
    form = SettingsForm(
        offline = util.strtobool(offline.value),
        registration = util.strtobool(registration.value)
    )
    if form.is_submitted():
        offline.value = str(form.offline.data)
        registration.value = str(form.registration.data)
        offline.save()
        registration.save()
        flash('Global settings saved successfully.')
    return render_template('main/global_settings.html', form=form)


@bp.route('/favicon.ico')
def favicon():
    return send_from_directory(os.path.join(current_app.root_path, 'static'), 'favicon.ico', mimetype='image/vnd.microsoft.icon')

app/templates/main/article_view.html
{% extends 'layout/layout.html' %}

{% block content %}
    <div>
        {% set filename = url_for('static', filename='images/articles/' ~ article.image | default('no-image.jpg', true)) %}
        <img src="{{ filename }}" class="img-thumbnail mx-auto d-block" alt="article's image" class="img-fluid">
        <p></p>
        <h2>{{ article.title }}</h2>
        <div>
            <p>{{ article.author.fullname }} - {{ article.createdat | localdatetime }}</p>
        </div>
        <div>
            {{ article.slug | safe }} {{ article.body | safe }}
        </div>
    </div>
{% endblock %}

app/templates/main/blank.html
{% extends 'layout/layout.html' %}

{% block content %}
    <p>This is a blank page.</p>
    <p>{{ request }}</p>
    <p>{{ config }}</p>
    <p>{{ session }}</p>
    <p>{{ current_user.roles }}</p>
{% endblock %}

app/templates/main/dashboard.html
{% extends 'layout/layout.html' %}

{% block breadcrumb %}
    <li class="breadcrumb-item active">{{ _('Dashbord') }}</li>
{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-xl-3 col-sm-6 mb-3">
            <div class="card text-white bg-primary o-hidden h-100">
                <div class="card-body">
                    <div class="card-body-icon">
                        <i class="fa fa-fw fa-users"></i>
                    </div>
                    <div class="mr-4">
                        <h1 class="d-inline">{{ data['users_count'] }}</h1>
                        <h2><small>{{ _('users') }}</small></h2>
                    </div>
                </div>
                <a class="card-footer text-white clearfix small z-1" href="{{ url_for('users.list') }}">
                    <span class="float-left">{{ _('List') }}</span>
                    <span class="float-right">
                <i class="fa fa-angle-right"></i>
              </span>
                </a>
            </div>
        </div>
        <div class="col-xl-3 col-sm-6 mb-3">
            <div class="card text-white bg-success o-hidden h-100">
                <div class="card-body">
                    <div class="card-body-icon">
                        <i class="fa fa-fw fa-newspaper-o"></i>
                    </div>
                    <div class="mr-4">
                        <h1 class="d-inline">{{ data['articles_count'] }}</h1>
                        <h2><small>{{ _('news') }}</small></h2>
                    </div>
                </div>
                <a class="card-footer text-white clearfix small z-1" href="{{ url_for('articles.list_view') }}">
                    <span class="float-left">{{ _('List') }}</span>
                    <span class="float-right">
                <i class="fa fa-angle-right"></i>
              </span>
                </a>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12 col-md-6">
            <div class="card mb-3">
                <div class="card-header">
                    <i class="fa fa-area-chart"></i> {{ _('Articles per User') }}</div>
                <div class="card-body">
                    <canvas id="articles-per-user" width="100%" height="30"></canvas>
                </div>
                <div class="card-footer small text-muted">&nbsp;</div>
            </div>
        </div>
        <div class="col-xs-12 col-md-6">
            <div class="card mb-3">
                <div class="card-header">
                    <i class="fa fa-area-chart"></i> {{ _('Articles per day') }}</div>
                <div class="card-body">
                    <canvas id="articlesAreaChart" width="100%" height="30"></canvas>
                </div>
                <div class="card-footer small text-muted">&nbsp;</div>
            </div>
        </div>
    </div>

    {% if current_user.has_role('Administrator') or current_user.has_role('Editor') %}
    <div class="row">
        <div class="col-lg-6">
            <div class="card">
                <div class="card-header">
                    <i class="fa fa-bell-o"></i> {{ _('Inactive articles') }}
                </div>
                <div class="list-group list-group-flush small">
                    {% for inactive in data['inactive_articles'] %}
                    <a class="list-group-item list-group-item-action" href="{{ url_for('articles.update', id=inactive.id) }}">
                        <div class="media">
                            {% set filename = url_for('static', filename='images/articles/' ~ inactive.image | default('no-image.jpg', true)) %}
                            <img class="d-flex mr-3 rounded-circle"
                                 src="{{ filename }}"
                                style="width: 60px; height:60px;">
                            <div class="media-body">
                                <strong>{{ inactive.title }}</strong>
                                <div class="text-muted smaller">{{ inactive.createdat.strftime('%d/%m/%Y %H:%M') }}</div>
                            </div>
                        </div>
                    </a>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    {% endif %}
{% endblock %}

{% block inlinejs %}
    <script>
    $(document).ready(function () {

        var ctx_articles = document.getElementById("articlesAreaChart");
        var articlesLineChart = new Chart(ctx_articles, {
            type: 'line',
            data: {
                labels: {{ data['articles_dates'] | tojson }},
                datasets: [{
                    label: "Posts",
                    lineTension: 0.3,
                    backgroundColor: "rgba(2,117,216,0.2)",
                    borderColor: "rgba(2,117,216,1)",
                    pointRadius: 5,
                    pointBackgroundColor: "rgba(2,117,216,1)",
                    pointBorderColor: "rgba(255,255,255,0.8)",
                    pointHoverRadius: 5,
                    pointHoverBackgroundColor: "rgba(2,117,216,1)",
                    pointHitRadius: 20,
                    pointBorderWidth: 2,
                    data: {{ data['articles'] }},
                }],
            },
            options: {
                scales: {
                    xAxes: [{
                        time: {
                            unit: 'date'
                        },
                        gridLines: {
                            display: false
                        },
                        ticks: {
                            maxTicksLimit: 7
                        }
                    }],
                    yAxes: [{
                        ticks: {
                            min: 0,
                            max: 20,
                            maxTicksLimit: 5
                        },
                        gridLines: {
                            color: "rgba(0, 0, 0, .125)",
                        }
                    }],
                },
                legend: {
                    display: false
                }
            }
        });

        var barChart = $("#articles-per-user");
        var chartLine = new Chart(barChart, {
            type: 'bar',
            data: {
                datasets: [
                    {
                        data: {{ data['articles_per_user'][1] | default('', true) | tojson }},
                        backgroundColor: '#26B99A',
                        label: "articles"
                    },
                ],
                labels: {{ data['articles_per_user'][0] | default([], true) | tojson }}
            },
            options: {
                scales: {
                    yAxes: [{
                        ticks: {
                            beginAtZero: !0,
                            stepSize: 1
                        }
                    }]
                }
            }
        });
    });

    </script>
{% endblock %}

app/templates/main/global_settings.html
{% extends 'layout/layout.html' %}

{% block content %}
    <div class="card mt-3">
        <div class="card-header">
            <h3>{{ _('Global Settings') }}</h3>
        </div>
        <div class="card-body">
            <form method="post">
                <div class="form-group">
                    {{ form.hidden_tag() }}
                </div>
                <div class="form-group">
                    <strong>{{ form.offline.label }}</strong>
                    <div>{{ form.offline }}</div>
                </div>
                <div class="form-group">
                    <strong>{{ form.registration.label }}</strong>
                    <div>{{ form.registration }}</div>
                </div>
                {{ form.submit(class='btn btn-success float-right') }}
            </form>
        </div>
    </div>
{% endblock %}

{% block inlinejs %}
    <script>
    $(document).ready(function () {
        {% with messages = get_flashed_messages() %}
            {% for message in messages %}
            PNotify.success({
                title: 'Saving Settings',
                text: '{{ message }}',
                styling: 'material',
            });
            {% endfor %}
        {% endwith %}

        $("#offline").bootstrapSwitch();

        $("#registration").bootstrapSwitch();
    })
    </script>
{% endblock %}

app/templates/main/index.html
{% extends 'layout/layout.html' %}

{% block content %}
    {% for row in articles | batch(3) %}
        <div class="row">
            {% for article in row %}
                <div class="col-lg-4">
                    <div class="card">
                        {% set filename = url_for('static', filename='images/articles/' ~ article.image | default('no-image.jpg', true)) %}
                        <img src="{{ filename }}" class="card-img-top" alt="article's image">
                        <div class="card-body">
                            <h5 class="card-title">
                                <a href="{{ url_for('main.view_article', article_id=article.id) }}" class="card-link">

                                    {{ article.title }}
                                </a>
                            </h5>
                            <p class="card-text">{{ article.slug | safe }}</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <p>&nbsp;</p>
    {% endfor %}
{% endblock %}

app/templates/main/search_list.html
{% extends 'layout/layout.html' %}

{% block content %}
    <ul>
    {% for article in articles %}
        <li><a href="{{ url_for('main.view_article', article_id=article.id) }}">{{ article.title }}</a></li>
        <p>{{ article.slug | safe }}</p>
    {% endfor %}
    </ul>
{% endblock %}

app/templates/main/sysinfo.html
{% extends 'layout/layout.html' %}

{% block breadcrumb %}
    <li class="breadcrumb-item">
        <a href="#collapseSettings" data-toggle="collapse" data-parent="#exampleAccordion">{{ _('Settings') }}</a>
    </li>
    <li class="breadcrumb-item active">{{ _('Information') }}</li>
{% endblock %}

{% block content %}
    <div class="card mt-3">
    <div class="card-header"><h3>{{ _('System Information') }}</h3></div>
    <div class="card-body">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>{{ _('Entity') }}</th>
                    <th>{{ _('Value') }}</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>{{ _('Operating System') }}</td>
                    <td>{{ data.platform_version }}</td>
                </tr>
                <tr>
                    <td>{{ _('Python') }}</td>
                    <td>{{ data.python_version }}</td>
                </tr>
                <tr>
                    <td>{{ _('Flask') }}</td>
                    <td>{{ flask_version() }}</td>
                </tr>
                <tr>
                    <td>{{ _('Host') }}</td>
                    <td>{{ request.host }}</td>
                </tr>
                <tr>
                    <td>{{ _('Database URI') }}</td>
                    <td>{{ config.get('SQLALCHEMY_DATABASE_URI') }}</td>
                </tr>
                <tr>
                    <td>{{ _('User Agent') }}</td>
                    <td>{{ request.user_agent }}</td>
                </tr>
                <tr>
                    <td>{{ _('Server Software') }}</td>
                    <td>{{ request.environ['SERVER_SOFTWARE'] }}</td>
                </tr>
                <tr>
                    <td>{{ _('Session Cookie Name') }}</td>
                    <td>{{ config.get('SESSION_COOKIE_NAME') }}</td>
                </tr>
                <tr>
                    <td>{{ _('Maximum Upload Filesize') }}</td>
                    <td>{{ config.get('MAX_CONTENT_LENGTH') | filesizeformat }}</td>
                </tr>
            </tbody>
        </table>
    </div>
{% endblock %}