app/articles/models.py
from .. import db
from datetime import datetime


class Article(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(128), nullable=False)
    slug = db.Column(db.String(256))
    body = db.Column(db.Text)
    image = db.Column(db.String(256))
    status = db.Column(db.Boolean)
    createdat = db.Column(db.DateTime, default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id', ondelete='CASCADE'))

    def save(self):
        db.session.add(self)
        db.session.commit()

    def delete(self):
        db.session.delete(self)
        db.session.commit()

    def __repr__(self):
        return '<Article: {}, {}>'.format(self.id, self.title)

app/articles/forms.py
from flask_wtf import FlaskForm
from wtforms import (
    StringField, SubmitField, BooleanField, FileField, TextAreaField, HiddenField, DateTimeField, SelectField
)
from wtforms.ext.sqlalchemy.fields import QuerySelectField
from wtforms.validators import Length
from flask_wtf.file import FileAllowed
from flask_babel import lazy_gettext as _l
from ..auth.models import User


class AddForm(FlaskForm):
    title = StringField(label=_l('Title'), validators=[Length(min=4, max=128)])
    slug = StringField(label=_l('Slug'), validators=[Length(min=3, max=256)])
    body = TextAreaField(label=_l('Body'))
    status = BooleanField(label=_l('Status'))
    image = FileField(label=_l('Image'), validators=[FileAllowed(['jpg', 'jpeg', 'png'], 'jpg or png')])
    submit = SubmitField(label=_l('Submit'))


class UpdateForm(AddForm):
    id = HiddenField(label='id')
    createdat = DateTimeField(label=_l('Created at'))
    del_image = BooleanField(label=_l('Delete'))


class SearchForm(FlaskForm):
    title = StringField(label='Title', validators=[Length(min=4, max=128)])
    author = QuerySelectField(label=_l('Author'), allow_blank=True, blank_text='')
    status = SelectField(label=_l('Status'), choices=[('', ''),(1, 'Active'),(0, 'Inactive')])

    def __init__(self, *args, **kwargs):
        super().__init__(**kwargs)
        self.author.query = User.query.all()

app/articles/__init__.py
from flask import Blueprint

bp = Blueprint('articles', __name__)

from . import models, forms, routes

app/articles/routes.py
from .models import Article
from .forms import AddForm, UpdateForm, SearchForm
from flask_login import current_user, login_required
from ..auth.decorators import role_required
from . import bp
from flask import render_template, request, flash, redirect, url_for, abort, current_app
from flask_babel import _
import os, uuid, re
from ..auth.models import User


@bp.route('/articles')
@login_required
@role_required('Administrator', 'Editor', 'User')
def list_view():
    # define search form and populate previous search criteria
    form = SearchForm(data=request.args.items())
    # because 'author' QuerySelectField has been populated with objects of type <User>
    # it won't be selected just with the id from query string (previous search criteria)
    # We get object User from id
    if request.args.get('author'):
        author = User.query.get(request.args.get('author'))
        form.author.data = author

    query_article = Article.query
    if request.args:
        for parameter in request.args.items():
            if parameter[0] == 'title' and parameter[1]:
                query_article = query_article.filter(Article.title.like('%' + parameter[1] + '%'))
            elif parameter[0] == 'author' and parameter[1] != '__None':
                query_article = query_article.join('author').filter(User.id == parameter[1])
            elif parameter[0] == 'status' and parameter[1] != '':
                query_article = query_article.filter(Article.status == parameter[1])
    page = request.args.get('page', 1, type=int)
    if current_user.has_role('Administrator') or current_user.has_role('Editor'):
        articles = query_article.order_by(Article.createdat).paginate(page, 10, False)
    else:
        articles = query_article.filter_by(user_id=current_user.id).paginate(page, 10, False)
    # pass search filter in pagination
    query_string = re.sub('page=\d*&*', '', request.query_string.decode('utf-8'))
    return render_template('articles/list.html', articles=articles, form=form, query_string=query_string)


@bp.route('/article/add', methods=['GET', 'POST'])
@login_required
@role_required('Administrator', 'Editor', 'User')
def add():
    form = AddForm()
    if form.validate_on_submit():
        article = Article()
        article.title = form.title.data
        article.slug = form.slug.data
        article.body = form.body.data
        article.status = form.status.data
        article.user_id = current_user.id
        article.image = upload_image(form.image.data)
        article.save()
        flash(_('Article saved successfully.'), category='success')
        return redirect(url_for('articles.list_view'))
    return render_template('articles/add.html', form=form)


@bp.route('/article/<int:id>', methods=['GET', 'POST'])
@login_required
@role_required('Administrator', 'Editor', 'User')
def update(id):
    article = Article.query.get(id)
    form = UpdateForm(obj=article)
    if not (current_user.has_role('Administrator') or current_user.has_role(
            'Editor')) and current_user.id != article.user_id:
        abort(403)
    if form.validate_on_submit():
        article.title = form.title.data
        article.slug = form.slug.data
        article.body = form.body.data
        article.status = form.status.data
        if form.del_image.data:
            delete_image(article.image)
            article.image = None
        if form.image.data:
            delete_image(article.image)
            article.image = upload_image(form.image.data)
        article.save()
        flash(_('Article saved successfully.'), category='success')
        return redirect(url_for('articles.list_view'))
    return render_template('articles/update.html', form=form)


def upload_image(imagedata):
    if imagedata:
        extension = os.path.splitext(imagedata.filename)[1]
        unique_filename = uuid.uuid4().hex + extension
        imagedata.save(os.path.join(current_app.config['ARTICLES_UPLOAD_FOLDER'], unique_filename))
        return unique_filename
    return None


@bp.route('/article/<int:article_id>/delete', methods=['POST'])
@login_required
@role_required('Administrator', 'Editor', 'User')
def delete(article_id):
    article = Article.query.get_or_404(article_id)
    if not (current_user.has_role('Administrator') or current_user.has_role(
            'Editor')) and current_user.id != article.createdby:
        abort(403)
    article.delete()
    delete_image(article.image)
    return redirect(url_for('articles.list_view'))


def delete_image(image):
    if image and os.path.exists(os.path.join(current_app.config['ARTICLES_UPLOAD_FOLDER'], image)):
        os.remove(os.path.join(current_app.config['ARTICLES_UPLOAD_FOLDER'], image))
        return True
    return False

app/templates/articles/add.html
{% extends 'layout/layout.html' %}
{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{{ url_for('articles.list_view') }}">Articles</a></li>
    <li class="breadcrumb-item active">{{ _('Add article') }}</li>
{% endblock %}
{% block content %}
    <div class="card mt-3">
        <div class="card-header"><h3>{{ _('Create a new article') }}</h3></div>
        <div class="card-body">
            <form method="post" action="" enctype="multipart/form-data" novalidate>
                <div class="form-group">
                    {{ form.hidden_tag() }}
                </div>
                <div class="form-group">
                    {{ form.title.label }}
                    {{ form.title(class='form-control') }}
                    {% for error in form.title.errors %}
                        <small class="form-text text-danger">{{ error }}</small>
                    {% endfor %}
                </div>
                <div class="form-group">
                    {{ form.slug.label }}
                    {{ form.slug(class='form-control') }}
                    <ul>
                        {% for error in form.slug.errors %}
                            <li>
                                <small class="form-text text-danger">{{ error }}</small>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="form-group">
                    {{ form.body.label }}
                    {{ form.body(class='form-control', rows=10) }}
                    <ul>
                        {% for error in form.body.errors %}
                            <li>
                                <small class="form-text text-danger">{{ error }}</small>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="form-group">
                    {{ form.status.label }}
                    <div>{{ form.status }}</div>
                </div>
                <div class="form-group">
                    {{ form.image.label }}
                    {{ form.image(class='form-control', style='height: auto;') }}
                    {% for error in form.image.errors %}
                        <small class="form-text text-danger">{{ error }}</small>
                    {% endfor %}
                </div>
                <div>
                    <button type="button" class="btn btn-primary float-right ml-1"
                            id="btn-cancel">{{ _('Cancel') }}</button>
                    {{ form.submit(class='btn btn-success float-right') }}
                </div>

            </form>
        </div>
    </div>
{% endblock %}

{% block inlinejs %}
    <script>
        $(document).ready(function () {
            $("#status").bootstrapSwitch();
            {% if current_user.has_role('User') %}
                $("#status").bootstrapSwitch('disabled', true);
            {% endif %}
            $("#btn-cancel").on("click", function () {
                window.location.assign("{{ url_for('main.index') }}");
            });

            $("#body").summernote({
                height: 300,
                toolbar: [
                    // [groupName, [list of button]]
                    ['style', ['bold', 'italic', 'underline', 'clear']],
                    ['font', ['strikethrough', 'superscript', 'subscript']],
                    ['fontsize', ['fontsize']],
                    ['color', ['color']],
                    ['para', ['ul', 'ol', 'paragraph']],
                    ['height', ['height']],
                    ['codeview']
                ],
            });

        });
    </script>
{% endblock %}

app/templates/articles/list.html
{% extends 'layout/layout.html' %}
{% from 'macro/pagination.html' import render_pagination %}
{% block breadcrumb %}
    <li class="breadcrumb-item active">{{ _('Articles') }}</li>
{% endblock %}
{% block content %}
    <div style="margin-bottom: 10px;">
        <a href="#search-filters" class="btn btn-secondary float-right ml-1" data-toggle="collapse" role="button" >
                {{ _('Filters') }}
        </a>
        <div class="clearfix"></div>
        <div class="collapse" id="search-filters">
            <form method="get">
                <div class="form-group">
                    {{ form.title.label }}
                    {{ form.title(class='form-control') }}
                </div>
                <div class="form-group">
                    {{ form.status.label }}
                    {{ form.status(class='form-control') }}
                </div>
                {% if current_user.has_role('Administrator') or current_user.has_role('Editor') %}
                <div class="form-group">
                    {{ form.author.label }}
                    {{ form.author(class='form-control') }}
                </div>
                {% endif %}
                <div class="form-group">
                    <button type="submit" class="btn btn-success float-right ml-1">{{ _('Search') }}</button>
                    <a href="{{ url_for('articles.list_view') }}" class="btn btn-light float-right ml-1">{{ _('Reset') }}</a>
                    <div class="clearfix"></div>
                </div>
            </form>
        </div>
    </div>
    <div class="card">
        <div class="card-header">
            <h3>{{ _('List of articles') }}</h3>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table">
                    <thead class="thead-ssecondary">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">{{ _('Title') }}</th>
                        <th scope="col">{{ _('Slug') }}</th>
                        <th scope="col">{{ _('Author') }}</th>
                        <th scope="col" class="text-center">{{ _('Status') }}</th>
                        <th scope="col" class="text-center">{{ _('Delete') }}</th>
                        <th scope="col" class="text-center">{{ _('Edit') }}</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for article in articles.items %}
                        <tr>
                            <th scope="row"><a href="{{ url_for('articles.update', id=article.id) }}">{{ article.id }}</a></th>
                            <td>{{ article.title }}</td>
                            <td>{{ article.slug | safe }}</td>
                            <td>{{ article.author.username }}</td>
                            <td class="text-center">
                                {% if article.status %}
                                    <i class="fa fa-check text-success fa-lg" title="Active">&nbsp;</i>
                                {% else %}
                                    <i class="fa fa-ban text-danger fa-lg" title="Inactive"></i>
                                {% endif %}
                            </td>
                            <td class="text-center">
                                <form method="post" action="{{ url_for('articles.delete', article_id=article.id) }}">
                                    <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#confirm-{{ article.id }}">
                                        <i class="fa fa-trash-o" title="{{ _('Delete article') }}"></i>
                                    </button>
                                    <div class="modal" id="confirm-{{ article.id }}">
                                        <div class="modal-dialog">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h4 class="modal-title">{{ _('Delete article') }}</h4>
                                                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                                                </div>
                                                <div class="modal-body">
                                                    {{ _('Please confirm the deletion of article') }}
                                                    &quot;{{ article.title }} &quot;
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-danger" data-dismiss="modal">
                                                        {{ _('No') }}
                                                    </button>
                                                    <button type="submit" class="btn btn-primary">
                                                        {{ _('Yes') }}
                                                    </button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </td>
                            <td class="text-center">
                                <a href="{{ url_for('articles.update', id=article.id) }}" class="btn btn-info" title="{{ _('Edit article') }}">
                                    <i class="fa fa-edit"></i></a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                    <tfoot>
                        <tr>
                            <td colspan="5">
                                {{ render_pagination(articles, 'articles.list_view') }}
                            </td>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

{% block inlinejs %}
    <script>
        $(document).ready(function () {
            $("#author, #status").select2({
                width: '100%'
            });

            {% with messages = get_flashed_messages() %}
            {% for message in messages %}
            PNotify.success({
                title: 'Saving article',
                text: '{{ message }}',
                styling: 'material',
            });
            {% endfor %}
            {% endwith %}
        });
    </script>
{% endblock %}

app/templates/articles/update.html
{% extends 'layout/layout.html' %}
{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{{ url_for('articles.list_view') }}">Articles</a></li>
    <li class="breadcrumb-item active">{{ _('Update article') }}</li>
{% endblock %}
{% block content %}
    <div class="card mt-3">
        <div class="card-header">
            <h3 class="float-left">{{ _('Update article with') }} {{ form.id.label }}: #{{ form.id.data }}</h3>
            <span class="float-right"><strong>{{ _('Created') }}:</strong>
                {{ form.createdat.data | localdatetime }}
            </span>
        </div>
        <div class="card-body">
            <form method="post" action="" enctype="multipart/form-data" novalidate>
                <div class="form-group">
                    {{ form.hidden_tag() }}
                </div>
                <div class="form-group">
                    {{ form.title.label }}
                    {{ form.title(class='form-control') }}
                    {% for error in form.title.errors %}
                        <small class="form-text text-danger">{{ error }}</small>
                    {% endfor %}
                </div>
                <div class="form-group">
                    {{ form.slug.label }}
                    {{ form.slug(class='form-control') }}
                    <ul>
                    {% for error in form.slug.errors %}
                        <li><small class="form-text text-danger">{{ error }}</small></li>
                    {% endfor %}
                    </ul>
                </div>
                <div class="form-group">
                    {{ form.body.label }}
                    {{ form.body(class='form-control', rows=10) }}
                    <ul>
                    {% for error in form.body.errors %}
                        <li><small class="form-text text-danger">{{ error }}</small></li>
                    {% endfor %}
                    </ul>
                </div>
                <div class="form-group">
                    {{ form.status.label }}
                    <div>{{ form.status }}</div>
                </div>
                {% if form.image.data is not none %}
                    <div class="form-group">
                        <label>{{ _('Existing image') }}</label>&nbsp;&nbsp;&nbsp;
                        <div class="form-control">
                            <span class="fa fa-image" aria-hidden="true" data-image-url="{{ form.image.data }}"></span>
                            &nbsp;&nbsp;&nbsp;
                            {{ form.del_image }}&nbsp;{{ form.del_image.label }}
                        </div>
                    </div>
                {% endif %}
                <div class="form-group">
                    {{ form.image.label }}
                    {{ form.image(class='form-control', style='height: auto;') }}
                    {% for error in form.image.errors %}
                        <small class="form-text text-danger">{{ error }}</small>
                    {% endfor %}
                </div>
                <div>
                    <button type="button" class="btn btn-primary float-right ml-1" id="btn-cancel">{{ _('Cancel') }}</button>
                    {{ form.submit(class='btn btn-success float-right') }}
                </div>

            </form>
        </div>
    </div>
{% endblock %}

{% block inlinejs %}
<script>
    $(document).ready(function () {
        $("#status").bootstrapSwitch();

        {% if current_user.has_role('User') %}
            $("#status").bootstrapSwitch('disabled', true);
        {% endif %}

        $("#btn-cancel").on("click", function () {
            window.location.assign("{{ url_for('articles.list_view') }}");
        });

        $(".fa-image").popover({
                'container': 'body',
                'title': 'Photo',
                'html': true,
                'trigger': 'hover',
                'content': function() {
                        return '<img src="{{ url_for('static', filename='images/articles/' ~ form.image.data) }}' + '" style="width:200px;" alt="user image">'
                    }
            });

        $("#body").summernote({
            height: 300,
            toolbar: [
                // [groupName, [list of button]]
                ['style', ['bold', 'italic', 'underline', 'clear']],
                ['font', ['strikethrough', 'superscript', 'subscript']],
                ['fontsize', ['fontsize']],
                ['color', ['color']],
                ['para', ['ul', 'ol', 'paragraph']],
                ['height', ['height']],
                ['codeview']
            ],
            codemirror: {
                theme: 'idea',
                lineNumbers: true,
                lineWrapping: true,
            },
        });

    });
</script>
{% endblock %}